### ISSUE TITLE
Can't compile LCD example 

### ISSUE THREAD

**Issue by jukebox** [amperka/ino#10]
Hi, 

i can't compile Helloworld example from :
https://github.com/Snootlab/Deuligne/tree/Arduino-1.0

juke@bouriquet:~/arduino/HelloWorld$ ino build
Searching for Board description file (boards.txt) ... /usr/share/arduino/hardware/arduino/boards.txt
Searching for Arduino lib version file (version.txt) ... /usr/share/arduino/lib/version.txt
Detecting Arduino software version ...  1.0 (1.0)
Searching for Arduino core library ... /usr/share/arduino/hardware/arduino/cores/arduino
Searching for Arduino standard libraries ... /usr/share/arduino/libraries
Searching for Arduino variants directory ... /usr/share/arduino/hardware/arduino/variants
Searching for avr-gcc ... /usr/bin/avr-gcc
Searching for avr-g++ ... /usr/bin/avr-g++
Searching for avr-ar ... /usr/bin/avr-ar
Searching for avr-objcopy ... /usr/bin/avr-objcopy
Scanning dependencies of src
Scanning dependencies of Deuligne
Scanning dependencies of Wire
src/sketch.cpp
Wire/utility/twi.c
Wire/Wire.cpp
Linking libWire.a
Deuligne/Deuligne.cpp
Linking libDeuligne.a
arduino/wiring_shift.c
arduino/wiring_digital.c
arduino/WInterrupts.c
arduino/wiring.c
arduino/wiring_analog.c
arduino/wiring_pulse.c
arduino/USBCore.cpp
arduino/HardwareSerial.cpp
arduino/CDC.cpp
arduino/WMath.cpp
arduino/Stream.cpp
arduino/HID.cpp
arduino/WString.cpp
arduino/new.cpp
arduino/Tone.cpp
arduino/IPAddress.cpp
arduino/Print.cpp
arduino/main.cpp
Linking libcore.a
Linking firmware.elf
.build/Deuligne/libDeuligne.a(Deuligne.o): In function `Deuligne::init()':
/home/juke/arduino/HelloWorld/lib/Deuligne/Deuligne.cpp:69: undefined reference to`Wire'
/home/juke/arduino/HelloWorld/lib/Deuligne/Deuligne.cpp:70: undefined reference to `Wire'
/home/juke/arduino/HelloWorld/lib/Deuligne/Deuligne.cpp:70: undefined reference to`TwoWire::beginTransmission(unsigned char)'
/home/juke/arduino/HelloWorld/lib/Deuligne/Deuligne.cpp:71: undefined reference to `TwoWire::write(unsigned char)'
/home/juke/arduino/HelloWorld/lib/Deuligne/Deuligne.cpp:71: undefined reference to`TwoWire::write(unsigned char)'
/home/juke/arduino/HelloWorld/lib/Deuligne/Deuligne.cpp:73: undefined reference to `TwoWire::endTransmission()'
make: **\* [.build/firmware.elf] Erreur 1

Works with arduino 1.0 ide

Thx

**Comment by nkrkv** [comment]
Hello. I've tried to reproduce the problem but build succeed on my machine. I guess the reason is in `.a`-files order while linking. Would you post your build log with `--verbose` option which is available since version 0.3.1?
